# Generated by Django 3.1.4 on 2021-01-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='aivo',
            new_name='ativo',
        ),
    ]
